### ISSUE TITLE
Category order / customization

### ISSUE THREAD

**Issue by s644** [joeattardi/picmo#131]
First of all thank you for this great plugin.

Is it possible to rearange the order of categories? I didn't find anything about this in the docs.
What I have found out so far is the possibility to display only specific categories as shown here

https://emoji-button.js.org/docs/customize

I tried to switch the order in the settings object and the group buttons in the picker did change the order but, and this might be a bug, too: all categories are still shown in the default order. Even though some of them should have been hidden by my custom configuration.
Your example shows the same habit. It's also not possible to click on categories to scroll to the specific section. In addition, emojis from other groups than 'smileys' & 'flags' are still visible. I tried it in FF and Chrome. It doesn't work in both browsers.

**Comment by saadbruno** [comment]
I didn't want to create a new issue, but this is definitely a bug.
Using `categories: ['smileys', 'animals', 'objects', 'people'],` does hide the category buttons, but the emojis are still shown on the list.

This even happens in the [documentation website](https://emoji-button.js.org/docs/customize)
![image](https://user-images.githubusercontent.com/23201434/114315925-98f87d00-9ad7-11eb-8128-afc2ea21beaa.png)

**Comment by joeattardi** [comment]
Will make sure to address this for v5.

**Comment by joeattardi** [comment]
This is fixed in the upcoming 5.0.0 release. Will close the issue upon release.

**Comment by joeattardi** [comment]
This issue is resolved in `v5.0.0-beta.6`.
