### ISSUE TITLE
Can you help to transpile to a single javascript file ? 

### ISSUE THREAD

**Issue by backandio** [joeattardi/picmo#134]
Hi.

I need to include this great lib in a old javascript code.
No module, import, etc...

Could you give instruction to generate a simple .min.js file to include in browser header ?

**Comment by joeattardi** [comment]
You can get the library as a standalone JavaScript file, easiest way is to use a CDN like unpkg:

https://unpkg.com/@joeattardi/emoji-button@4.6.0/dist/index.js

However, this will only work on browsers that support ES modules, which is currently all modern browsers (not IE11, which wouldn't work with Emoji Button anyway for other reasons).

Hope this helps.

**Comment by joeattardi** [comment]
Update on this: For the upcoming version 5 of Emoji Button, you will once again be able to use it as a UMD module as well as an ES module. Older browsers such as IE11 still won't be supported but this will hopefully support more application designs. Stay tuned.

**Comment by joeattardi** [comment]
The upcoming 5.0.0 release will include a UMD build as well as an ESM build, in addition to an npm module for bundler use. The docs will contain examples of these use cases. Coming soon!

**Comment by joeattardi** [comment]
This issue is resolved in `v5.0.0-beta.6`.
