### ISSUE TITLE
not closing the picker when clicking elsewhere or esc

### ISSUE THREAD

**Issue by Blazzze** [joeattardi/picmo#136]
[feature request]
could be cool to add an option to prevent it from closing when clicking elsewhere
i couldn't find this settings anywhere.

thanks :)

**Comment by cyberfly** [comment]
@Blazzze you can via the config https://emoji-button.js.org/docs/customize

**Comment by joeattardi** [comment]
This can be added, however keep in mind then the only way to close the picker will be either to pick an emoji (unless you disable auto-hide) or to explicitly call `hidePicker`. Which, if that's what your use case calls for, is totally reasonable. I can definitely include this option in the upcoming v5.

**Comment by joeattardi** [comment]
This has been implemented and will be included in the 5.0 release which should be in beta soon!

**Comment by joeattardi** [comment]
This issue is resolved in `v5.0.0-beta.6`.
