### ISSUE TITLE
Screen reader is not announcing status message "No emojis found" after searching for emoji by typing letters in "Search emojis" edit field.

### ISSUE THREAD

**Issue by pranshu512** [joeattardi/picmo#164]
### **Repro Steps:**

1. Tab to "Emoji" button available in any application and press enter.
2. Start Narrator and then TAB to "Search emoji" edit box and type any letters to get status message "No emojis found".
3. Observe that the narrator is not announcing any status message when there are no results are found.

### **Actual:**
After searching emoji if there is no results found then narrator is not announcing any status message such as "No emoji found".

**This issue is also observed with Chrome+ NVDA.**

### **Expected:**
The narrator should announce status message when there is no results are found such as "No emoji found".

### **User Impact:**
Screen reader users won't be able to understand whether the results are found or not.

**Comment by joeattardi** [comment]
Thanks for reporting this! This will be addressed for the 5.0 release.

**Comment by joeattardi** [comment]
Hi! This issue has been fixed and will be available in the next 5.0.0 beta release.

I only have VoiceOver on the Mac to test with, but in my testing, it immediately announced "No results found", so I believe this fixes the issue. I will be publishing a new beta release soon with several recent fixes.
