### ISSUE TITLE
question & request for custom emojis (with categories) 

### ISSUE THREAD

**Issue by despecial** [joeattardi/picmo#167]
Very nice script, got some questions and suggestions:

1.) Is it possible to show/use only custom emojis?

2.) Can you add support for category names for custom emojis (and maybe custom category names)?

The script already supports a list to show certain categories, this would be helpful to include custom categories.

**Comment by despecial** [comment]
3.) Custom emojis are not replaced immediately (only :emojicode gets inserted).
Any idea/chance to change this, so the editor area has a live preview within the content?

**Comment by Ionys320** [comment]
I agree, it would be nice!

**Comment by joeattardi** [comment]
The upcoming 5.0.0 release does not support multiple custom emoji categories - they are all contained in a single "Custom" category. They do, however, now support specifying tags that you can search by.

Custom emoji categories is a future consideration on the roadmap.
