### ISSUE TITLE
RTL is ignored for category name

### ISSUE THREAD

**Issue by jomarek** [joeattardi/picmo#168]
Categories names are always aligned to left even when website is RTL.
This is due to [this line](https://github.com/joeattardi/emoji-button/blob/d859569bb3d9d9180c2479699396e0ec5bc7b899/css/emoji-button.css#L388) in the CSS file.
As it's possible to use custom categories names it would be great if either RTL was supported by default or if there was an option to set alignment of categories names via the API.

![emojiRtl](https://user-images.githubusercontent.com/67270210/126308374-c99ee3eb-214c-4d29-abac-1d4e21f7a402.gif)

**Comment by joeattardi** [comment]
Thanks for reporting this! I don't think the CSS text-align property honors RTL languages. I think if I change this to use flex box and flex-start, it should work properly on both LTR and RTL.

**Comment by joeattardi** [comment]
This is resolved in v5. I will close this issue once v5 is released.

**Comment by joeattardi** [comment]
This issue is resolved in `v5.0.0-beta.6`.
