### ISSUE TITLE
autoFocusSearch still set's focus on keyDown

### ISSUE THREAD

**Issue by Lurkars** [joeattardi/picmo#170]
I would suggest if autoFocusSearch is set to false, also the keyDown event prevents from focusing. So in
https://github.com/joeattardi/emoji-button/blob/d859569bb3d9d9180c2479699396e0ec5bc7b899/src/index.ts#L718
 I suggest changing `} else if (event.key.match(/^[\w]$/) && this.search) {` to `} else if (event.key.match(/^[\w]$/) && this.search && this.options.autoFocusSearch) {` or adding a separate option for disabling autofocus on keydown.

**Comment by joeattardi** [comment]
This works a little differently with PicMo 5; keydown events don't automatically focus search. There is now a shortcut key: Command+S/Control+S that will jump to the search field.
