### ISSUE TITLE
with auto hide off, after selection, picker selector returns to default category/emoji

### ISSUE THREAD

**Issue by mcote7** [joeattardi/picmo#172]
with autohide off, after a user selects an emoji it returns back to the initial category & emoji, so if you want to select the same emoji multiple times you have to keep re-selecting the proper category/emoji

screen capture of current behavior  -  
https://drive.google.com/file/d/1ZtEOqFPHJte1JbNIlND78aE_KZCgGvGq/view?usp=sharing

**Comment by joeattardi** [comment]
This is fixed in the upcoming 5.0.0 release. Will close the issue upon release.

**Comment by mcote7** [comment]
thank you sir, love the picker

**Comment by joeattardi** [comment]
This issue is resolved in `v5.0.0-beta.6`.
