### ISSUE TITLE
recentsCount doesn't apply

### ISSUE THREAD

**Issue by jicihome** [joeattardi/picmo#187]
It's all in the title. Recents count is set to 8 but show a lot more.

**Comment by jicihome** [comment]
Nevermind. Seem that if you change it while you was testing before and doesn't select a new emoji, the list stay on the previous #. As soon as you select a new one, it get updated to the limit

**Comment by joeattardi** [comment]
I think this is still a valid issue! If the maxRecents has changed and there are too many recents stored, it can truncate them to meet the new limit. 

I'll make sure to include this in the v5 release! Reopening to track it.
