### ISSUE TITLE
`className` not working?

### ISSUE THREAD

**Issue by hognevevle** [joeattardi/picmo#192]
Hi there!

I'm trying to override the styling of the picker, but after specifying a `className` and adding my styles, I'm not seeing any results. In my case, I've used `my-picker` as the `className`, but there is no reflection of this in the DOM (the class "my-picker" doesn't appear anywhere), and hence, my style overrides are never applied. 

As you can see, I'm using this together with `createPopup` - is it possible there is a bug here?

<img width="933" alt="CleanShot 2022-05-14 at 00 04 08@2x" src="https://user-images.githubusercontent.com/2721188/168395209-542ab92a-5615-4346-859a-1e948cefd93e.png">

<img width="304" alt="CleanShot 2022-05-14 at 00 06 34@2x" src="https://user-images.githubusercontent.com/2721188/168395385-7a9683aa-2c0d-4e78-a947-8cfa085adb1a.png">

**Comment by joeattardi** [comment]
Hi, thanks for trying the beta version! I just gave this a try and it seems to work, even for popup pickers.

Can you verify that you are using version `5.0.0-beta.8`? That is the version the custom theme support was added in.

To make sure you have the latest beta you can run `npm install picmo@beta` - I goofed and forgot to specify the beta tag on an earlier version so if you did `npm install picmo` alone you probably have `5.0.0-beta.7`. 

Can you try `npm install picmo@beta` and see if that resolves the issue? Thanks again! I'll leave the issue open until I hear back.

**Comment by hognevevle** [comment]
Thank you for the pointer @joeattardi, I was indeed on `5.0.0-beta.7` of `picmo`, and in fact `5.0.0-beta.4` of `picmo/popup-picker`. After upgrading both to the latest `5.0.0-beta.9`, it is now working as expected. 🚀
