### ISSUE TITLE
PickerOptions not working

### ISSUE THREAD

**Issue by reflexLabs** [joeattardi/picmo#194]
I'm trying to modify picker options with `PickerOptions` but when I apply it it doesn't do anything, I tried like this:
```
const picker = createPicker({
      rootElement,
      showPreview: false,
      PickerOptions:{
        emojisPerRow: 4,
        visibleRows: 4,
        emojiSize: 1
      },
      theme: darkTheme
    });
```
on the top of the module file I have:
```
import { createPicker, darkTheme } from 'https://unpkg.com/picmo@5.0.0-beta.7/dist/index.js';
```
When I try to import PickerOptions it's not finding it (since it's on other path but I can't find it [types])

What I'm doing wrong?

BTW:
When I count emojies in input every single emoji considered as 2 length because it's consists of 2 words, so how can I consider it as 1 character instead of 2?

Thanks!

**Comment by reflexLabs** [comment]
My fault, I used it wrong, this is how it should be used:
```
const picker = createPicker({
      rootElement,
      showPreview: false,
      emojisPerRow: 4,
      visibleRows: 4,
      emojiSize: 1,
      theme: darkTheme
    });
```

**Comment by joeattardi** [comment]
Yes, that looks correct now. PickerOptions is a type alias only, not a property name. 

Thanks for trying the beta!
