### ISSUE TITLE
showCloseButton error

### ISSUE THREAD

**Issue by levipadre** [joeattardi/picmo#196]
Hi,

`showCloseButton: false` code does hide the close button, but it also gives an error and can't close the popup anymore. The error message is: "TypeError: Cannot read properties of undefined (reading 'animate')"

**Comment by joeattardi** [comment]
Good catch, thanks for reporting this! I'll get this fixed today and publish a new version.

**Comment by joeattardi** [comment]
Good to go, I just published v5.0.1 which includes a fix for this.

**Comment by levipadre** [comment]
Thanks, that was super quick. It's good now indeed.
