### ISSUE TITLE
Class to top level

### ISSUE THREAD

**Issue by levipadre** [joeattardi/picmo#198]
Hi,

Maybe I just can't find in the doc, but is there a way to add class to the very top level of the popup?
I can catch that with `[class*="popupPicker_popupContainer"]` for example, but it would be great a defined class. For instance I need to change the z-index, but it can be anything of course.
With the class name we could change also the style of the close button a bit easier.

**Comment by Ionys320** [comment]
I have the same issue by using Tailwind and the z-index classes with PicMo : it's not useful because custom classes are not on the top container.

**Comment by levipadre** [comment]
Thanks man! The top classname would be the best, but you can add the zIndex to the options as well, it won't interfere. I think it was in the previous version as well. Thank you for the great support. Everyone should do the same way you do 👍

**Comment by joeattardi** [comment]
Fixed in 5.1.0! The popup options object now supports a `className` option that can be used to change the z-index.
