### ISSUE TITLE
Feed the emoji recents palette externally

### ISSUE THREAD

**Issue by orlandoaleman** [joeattardi/picmo#202]
It would be very interesting (for my case) if the most recent emojis could be indicated through callbacks. Currently, what I have done is modify some things to achieve it. Why? Because it allows me to synchronize emoji statistics between the mobile phone and the web.

On the other hand, I would like to thank you for the work you do in this utility.

**Comment by joeattardi** [comment]
This is a great idea! Don't know how I missed thinking of it 😂

Having an external store via callbacks or something for recents is a great concept, after all just using local storage is pretty limited. 

I will absolutely put this on the roadmap for the next significant feature update. 

It will probably be some time though. I got myself quite burnt out finishing the 5.0.0 release. I will definitely fix bugs that come up but new features will need to wait a while. 

I do keep a roadmap document and will definitely add it!

You could sort of fake this by managing the local storage externally to the picker. You could set the recents data in the local storage key before creating the picker, and whenever an 'emoji:select' event fires you could maintain that state in sync. 

The format isn't currently documented in the docs but you can find it in the source code. 

Anyway thanks again for the idea!

I do maintain a Twitter account @picmojs where announcements and such will be posted going forward!

**Comment by orlandoaleman** [comment]
In [this fork](https://github.com/orlandoaleman/emoji-button) I've made some changes that maybe you can use as a base. They are few and small, because really your work is very complete. By the way, I have also used callbacks to able to modify/translate the emoji titles.

**Comment by joeattardi** [comment]
Imlpemented in 5.2.0. See [the docs](https://picmojs.com/docs/usage/recent-emojis) for details.
