### ISSUE TITLE
When I toggle on picker the page jumps up 

### ISSUE THREAD

**Issue by reflexLabs** [joeattardi/picmo#203]
I notice that when I toggle on the emoji picker it cause the window to scroll up a bit to fit the picker to screen, how can I cancel it?

**Comment by joeattardi** [comment]
It could be a Popper.js issue. Try experimenting with the position options?

Can you fork this CodeSandbox (https://codesandbox.io/s/picmo-popup-demo-6fyoew) and see if you can provide a reproducible case with it?

Thanks!

**Comment by joeattardi** [comment]
@reflexLabs Any update on this?

**Comment by joeattardi** [comment]
I can't see what's going on if you don't provide a working code example. Please create a CodePen/CodeSandbox or the like with your code that exhibits the issue. Thanks!

**Comment by joeattardi** [comment]
Closing due to no response. Feel free to reopen in the future if you can provide some sample code.
