### ISSUE TITLE
[Feature Request] Support Facebook Emoji

### ISSUE THREAD

**Issue by carl-jin** [joeattardi/picmo#204]
Hi, Could We support Facebook Emoji?

**Comment by carl-jin** [comment]
Use [picmo-facebook-emoji-renderer](https://www.npmjs.com/package/picmo-facebook-emoji-renderer)

**Comment by joeattardi** [comment]
Hey, cool! A third party renderer package - I like it! 😄 

Two very minor notes:

- In `package.json`, the keyword `"pickmo"` is misspelled (should be "picmo")
- Currently `picmo` is listed as a dependency, this should probably be a peer dependency.
