### ISSUE TITLE
Uncaught (in promise): [IDBOpenDBRequest] A mutation operation was attempted on a database that did not allow mutations.

### ISSUE THREAD

**Issue by peremarshall** [joeattardi/picmo#208]
The library doesn't appear to work in Firefox, when browsing in a private window. It sounds like this may be an issue with 
IndexedDB support.

- https://stackoverflow.com/questions/12182320/indexeddb-error-a-mutation-operation-was-attempted-on-a-database-that-did-not-a
- https://bugzilla.mozilla.org/show_bug.cgi?id=1639542
- https://github.com/jakearchibald/idb/issues/81

I'm not sure if this matters, but I thought I'd let you know!

**Comment by joeattardi** [comment]
If IndexedDB isn't available, PicMo has an option to use a simple in-memory datastore. You'll take a performance and memory cost but it should get around that. More details [here](https://picmojs.com/docs/usage/emoji-data#in-memory-data-store).
