### ISSUE TITLE
Using TwemojiRenderer with Svelte causes an error.

### ISSUE THREAD

**Issue by embedvr** [joeattardi/picmo#212]
Hey! I'm not entirely sure what the problem is with this but I am trying to use Picmo in a SvelteKit project but for some reason importing `@picmo/renderer-twemoji` causes an error.

Error:
```
Vite Error, /node_modules/.vite/deps/@picmo_renderer-twemoji.js?v=2ea3ef85 optimized info should be defined
```

Line causing the issue: 

```
import { TwemojiRenderer } from '@picmo/renderer-twemoji';
```

**Comment by joeattardi** [comment]
Unfortunately I know zero about SvelteKit or Vite! I will try to help however I can though!

Two questions...

1. Do you get the same error with the base `picmo` import?
2. Are you able to set up a CodePen/CodeSandbox/StackBlitz or the like with an example showing this error?

Thanks and sorry for the issue!

**Comment by embedvr** [comment]
> Unfortunately I know zero about SvelteKit or Vite! I will try to help however I can though!
> 
> Two questions...
> 
>     1. Do you get the same error with the base `picmo` import?
> 
>     2. Are you able to set up a CodePen/CodeSandbox/StackBlitz or the like with an example showing this error?
> 
> 
> Thanks and sorry for the issue!

I do not get the error using the base `picmo` package import and the emoji popup picker works at the moment. I can try to setup one of those websites but I have never used one before so not entirely sure how. Will figure it out.

**Comment by joeattardi** [comment]
No problem, it's useful information that this only happens with the twemoji renderer. I may have goofed on how I am packaging it, let me take a look.

**Comment by joeattardi** [comment]
Can you at least paste in the specific file you're importing the Twemoji renderer from? Maybe I can try creating a skeleton SvelteKit project and using the same code.

**Comment by embedvr** [comment]
Weirdly enough, the bug seems to have completely vanished.

**Comment by joeattardi** [comment]
Those are the best kind! 😆

**Comment by joeattardi** [comment]
I will close this then, feel free to re-open with additional details if it comes back.
