### ISSUE TITLE
Invalid CSS for `scrollbar-width`

### ISSUE THREAD

**Issue by ahukkanen** [joeattardi/picmo#226]
The following lines contain invalid CSS:
https://github.com/joeattardi/picmo/blob/282204cbab6d81d97b14773e2ab4aeb871fdadb0/packages/picmo/src/views/EmojiArea.scss#L6

https://github.com/joeattardi/picmo/blob/81e9faec3f51e7c6f82b8f1fd9dbf26f8b93a2b5/packages/picmo/src/views/EmojiPicker.scss#L211

You can try this here:
https://jigsaw.w3.org/css-validator/validator.html.en#validate_by_input

By entering this CSS to the direct input:
```css
.test {
  scrollbar-width: 8px;
}
```

Accepted values for the definition are `auto`, `thin`, `none` or one of the global values (`inherit`, `initial`, `revert`, `revert-layer` or `unset`).

More information:
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

**Comment by joeattardi** [comment]
Thanks for reporting this! This has been fixed and will be included in the next release.
