### ISSUE TITLE
Popup picker close button submits the form if the picker is inside a form

### ISSUE THREAD

**Issue by ahukkanen** [joeattardi/picmo#227]
If you provide a `rootElement` to the `createPopup` method within the `popupOptions` and the element happens to be inside a form, clicking the close popup button `[ X ]` will also submit the form.

The button is created here:
https://github.com/joeattardi/picmo/blob/9948a812ba13e99cb66722c8ec5c60812c643a44/packages/popup-picker/src/popupPicker.ts#L43

To fix this, the `button` should have a `type="button"` attribute on it.

Example:
https://jsfiddle.net/vp87f9d4/

**Comment by joeattardi** [comment]
Thanks for catching this! I missed this when I did an earlier fix for the emoji buttons doing the same thing. This will be included in the next release.

**Comment by MateoLa** [comment]
This problem should be reopened, it still occurs. Thank you
