### ISSUE TITLE
Update 5.5.1 broke integration

### ISSUE THREAD

**Issue by vnihoul77** [joeattardi/picmo#233]
Hi,
The new update released during the night seems to have broken my integration.
I am using the PopupPicker and now the `.open()` triggers the following error:

<img width="450" alt="Screen Shot 2022-08-17 at 10 26 58" src="https://user-images.githubusercontent.com/4152545/185071788-c2f618dd-8a06-4d4c-8053-54fa3332a19f.png">

The popup still shows though the positioning seems also broken (popup is attached to page corner).

I am using the UMD versions
```
<script src="https://cdn.jsdelivr.net/npm/picmo@latest/dist/umd/index.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@picmo/popup-picker@latest/dist/umd/index.js"></script>
```

**Comment by joeattardi** [comment]
Ugh! Sorry about that. Missed a piece of the configuration to remove that at build time.

Just pushed 5.5.2 which removes this. jsdelivr doesn't seem to be updated yet with the `@latest` tag, should be soon, but in the meantime if you specify `@5.5.2` this problem should go away.
