### ISSUE TITLE
Cannot access private method

### ISSUE THREAD

**Issue by v1r0x** [joeattardi/picmo#234]
I switched from the old emoji-button to picmo and tried to setup a popup picker, but when starting my site all I get is a `Cannot access private method` error on the `addEventListener` method.
I'm running latest 5.5.2 on vue3

```javascript
import { createPopup } from '@picmo/popup-picker';

export default {
setup() {
const state = reactive({
    id: `emoji-picker-button`,
    picker: null,
});

onMounted(_ => {
    const trigger = document.getElementById(state.idd);

    state.picker = createPopup({
        hideOnEmojiSelect: false,
        position: 'bottom-end',
    }, {
        triggerElement: trigger,
        referenceElement: trigger,
        position: 'bottom-end',
    });

    emojiButton.addEventListener('click', _ => {
        state.picker.toggle();
    });

    state.picker.addEventListener('emoji:select', event => {
        console.log("selected emoji", event);
    });
});
}
}
```

**Comment by typhoon11** [comment]
hideOnEmojiSelect and position are popup options not picker options so it should be in the down one

**Comment by v1r0x** [comment]
Thanks for that info!

Unfortunately, this makes no difference in the error message

**Comment by typhoon11** [comment]
I am assuming it's coming from the state object thing, I don't have enough knowledge in vue but I am guess that it's not able to access state object.

**Comment by joeattardi** [comment]
What was the issue/fix?

**Comment by v1r0x** [comment]
Using the reactive state was the issue. Replacing `state.picker = createPopup(...)` with `const picker = createPopup(...)` fixed it.

**Comment by joeattardi** [comment]
Interesting. I can't think of anything that changed which would cause this issue, but then again I know nothing about Vue!
