### ISSUE TITLE
Add the option to choose reference Element in picker.toggle()

### ISSUE THREAD

**Issue by typhoon11** [joeattardi/picmo#237]
Like we had the option to pass the HTML element in togglePicker of Emoji Button it will be good if there is option to pass an element in toggle function or allow to pass array of elements in reference Elements, because I have many buttons with class `trigger` and I want the picker to be referenced there to all. 

Emoji Button:
![image](https://user-images.githubusercontent.com/66431066/185734911-086ebe87-4855-463d-8785-6e3a14d6b528.png)

Picmo:
![image](https://user-images.githubusercontent.com/66431066/185734928-eb8f2acc-36c2-4682-b222-d0d91e01de26.png)

**Comment by joeattardi** [comment]
Sorry I missed this during the redesign! I have just published v5.6.0 that includes this. The `open` and `toggle` methods now accept an optional object that can have a new `triggerElement` and `referenceElement`.

Updated API docs here: https://picmojs.com/docs/api/popup-picker/classes/popup-picker-controller/#open

See also: https://picmojs.com/docs/usage/popup-picker#sharing-a-popup-between-elements
