### ISSUE TITLE
Popup picker "jumping" effect after upgrade 5.4.0 -> 5.6.0

### ISSUE THREAD

**Issue by ahukkanen** [joeattardi/picmo#240]
I was upgrading Picmo to 5.6.0 from 5.4.2 (and `@picmo/popup-picker` from 5.4.0) and after the upgrade we got this kind of "jumping" effect on the first open of the picker:

https://user-images.githubusercontent.com/864340/186369762-7ad54bdb-2a60-44fe-9635-e875f4e31da3.mp4

This only happens after the upgrade. With `picmo` 5.4.2 + `@picmo/popup-picker` 5.4.0 this did not happen.

At the second part of the video I am showing this demo:
https://jsfiddle.net/yxo7gs5k/2/
https://jsfiddle.net/yxo7gs5k/2/show

In that demo I have overridden the `open` method from here to emphasize the issue we are having (and with the console log to show what's happening at what stage):
https://github.com/joeattardi/picmo/blob/7a996dbc0a94a771beba573a66861e7484b7a0b9/packages/popup-picker/src/popupPicker.ts#L151-L173

So the problem is coming from calling `this.picker.reset()` during the popup open which first focuses the picker element when it is wrongly positioned (in the actual integration) and then focuses it again when it is correctly positioned.

The reset call is calling `reset()` on the `EmojiArea` instance here:
https://github.com/joeattardi/picmo/blob/7a996dbc0a94a771beba573a66861e7484b7a0b9/packages/picmo/src/views/EmojiPicker.ts#L373

Which is actually causing the extra focus causing the jumping effect. If it would be called with the `false` argument (i.e. `performFocus = false`), it would fix the bug.

Here is the actual initialization code we are using for the popup picker:
https://github.com/decidim/decidim/blob/40e8fa0bc33ce64895aea54e41904f0be26d06b4/decidim-core/app/packs/src/decidim/input_emoji.js#L69-L77

And this is how the picker is opened when the emoji button is clicked:
https://github.com/decidim/decidim/blob/40e8fa0bc33ce64895aea54e41904f0be26d06b4/decidim-core/app/packs/src/decidim/input_emoji.js#L83

**Comment by ahukkanen** [comment]
For the time being I am fixing the bug by overriding the `open()` method on the `PopupPickerController` to handle the picker reset as follows:
https://github.com/decidim/decidim/blob/6d01a6615197dc0977d0a228e8c2ae71f7a7cc51/decidim-core/app/packs/src/decidim/input_emoji.js#L61-L69

The only change to the original code here is this line where I'm passing `false` to the `performFocus` argument:
https://github.com/decidim/decidim/blob/6d01a6615197dc0977d0a228e8c2ae71f7a7cc51/decidim-core/app/packs/src/decidim/input_emoji.js#L63

**Comment by joeattardi** [comment]
Thanks for reporting this and the detailed reproduction steps. I _think_  I have a working solution for this, which also fixes the problem of the picker appearing before it's properly positioned, then animating open again.

Not ready to publish yet as I want to include a couple of other items, if you want you can test it out locally by cloning the repository, running `npm install` and `npm run build`, then running `npx lerna link`. Finally from your project, run `npm link picmo` and `npm link @picmo/popup-picker`.

Let me know if you are successful!

**Comment by ahukkanen** [comment]
@joeattardi Thanks for the quick fixes once again!

I can confirm that running the unreleased GitHub version fixes the problem shown in the video. I will eagerly wait for the new release!

**Comment by joeattardi** [comment]
Great! I just released 5.6.1 which should include the fix.
