### ISSUE TITLE
Close button not working

### ISSUE THREAD

**Issue by MicJarek** [joeattardi/picmo#244]
Great plugin. But it seems that the 'Close' X button doesn't work in all cases. I set:
hideOnClickOutside: false,
hideOnEmojiSelect: false,
hideOnEscape: true,
showCloseButton: true

And the Escape works fine, but clicking the close button does nothing. You can replicate this in your own example:
https://picmojs.com/storybook/?path=/story/popup-emoji-picker--native&args=hideOnEmojiSelect:false;hideOnClickOutside:false

Thanks for your help... ☺️

**Comment by joeattardi** [comment]
Just published v5.6.3 which should fix this issue. Thanks for the report!

**Comment by MicJarek** [comment]
Awesome... Tks Joe... ☺️
