### ISSUE TITLE
Changing to dark theme after the creation of a picker does not update the bottom preview

### ISSUE THREAD

**Issue by Justsnoopy30** [joeattardi/picmo#247]
It only seems to happen when switching from light theme to dark, and only when calling updateOptions after the picker has been created. See below for screenshot:
![Screenshot from 2022-10-25 20-31-15](https://user-images.githubusercontent.com/33374736/197913539-7aec298a-9e5d-42e2-950b-8809e285e76d.png)

**Comment by joeattardi** [comment]
Seems to only affect popup pickers, interesting.

**Comment by joeattardi** [comment]
Just published 5.7.2 which hopefully will resolve this for you, please reopen if you still have issues!

**Comment by Justsnoopy30** [comment]
Still seems a bit off, but it's closer. The preview is incorrect (it should be gray but it's black) and there are white pixels around the border of the emoji picker if you look closely. 

Created with dark theme:
![image](https://user-images.githubusercontent.com/33374736/197935141-bf3049f1-ea8e-47a8-8623-02b43151849d.png)

Switched to dark theme after creation:
![image](https://user-images.githubusercontent.com/33374736/197935261-afdcc24e-a66c-41da-9584-dd84d58f44fd.png)

**Comment by Justsnoopy30** [comment]
There is no button for me to reopen the issue @joeattardi 
![image](https://user-images.githubusercontent.com/33374736/197935629-143dc632-ac06-4e17-b8c0-bb146845af1d.png)

**Comment by Justsnoopy30** [comment]
Ah nevermind maybe it wasn't fully updated or something, can't replicate it again. Also realized it's supposed to be black at the bottom after comparing with the demo on the site. Thanks.

**Comment by Justsnoopy30** [comment]
Minor nitpick, it still shows small white pixels around the edges when I switch to dark from light. Can reproduce that every time.
