### ISSUE TITLE
White/black opposite color pixels around edges of emoji picker after switching theme after the picker has been created

### ISSUE THREAD

**Issue by Justsnoopy30** [joeattardi/picmo#249]
It happens even after the fixes in the 5.7.1 update. I had to open a new issue because I could not reopen the old one.
Screenshot:
![image](https://user-images.githubusercontent.com/33374736/198704498-c79d9967-078b-4e2e-bb80-756bef5d19e7.png)

**Comment by joeattardi** [comment]
Hey, sorry for the delay on responding to this. I'll take a look at this this week.

**Comment by joeattardi** [comment]
Can you create a CodePen or other live example showing this? I am switching the theme and I don't see these pixels.
