### ISSUE TITLE
Class names get conflicted

### ISSUE THREAD

**Issue by Mizan-Rifat** [joeattardi/picmo#253]
Nice library. but the problem is you have styled it with some generic class names like content, header which creates conflict with theme classes. You should style with child selector.

**Comment by joeattardi** [comment]
Just published a new release, 5.7.3, that should resolve this issue. Please let me know or reopen if you still have issues!

**Comment by Mizan-Rifat** [comment]
Yeah, it's working but I found a new issue...
https://github.com/joeattardi/picmo/issues/259
