### ISSUE TITLE
Error when import from cdn

### ISSUE THREAD

**Issue by Punisheroot** [joeattardi/picmo#254]
Uncaught TypeError: Cannot read properties of undefined (reading 'createStyleInjector')
    at index.js:2:8
    at index.js:1:200
    at index.js:1:229

**Comment by joeattardi** [comment]
This isn't enough for me to figure out what's going on.

- Please create a CodePen/CodeSandbox/etc. that shows the issue you're having.
- What browser and version?

**Comment by Punisheroot** [comment]
> This isn't enough for me to figure out what's going on.
> 
> * Please create a CodePen/CodeSandbox/etc. that shows the issue you're having.
> * What browser and version?

There isn't any type of code.. only import generate the error.

1) https://codepen.io/thepipponer/pen/QWBprdB
2) Google Chrome 108.0.5359.125

**Comment by joeattardi** [comment]
I see it now!

You're loading the popup picker module, but not the base picmo module. `createStyleInjector` is in the `picmo` package.

If you add another `script` tag that loads picmo first, the error should go away:

```html
<script src="https://unpkg.com/picmo@latest/dist/umd/index.js"></script>
<script src="https://unpkg.com/@picmo/popup-picker@latest/dist/umd/index.js"></script>
```

Let me know if this fixes the issue for you!

**Comment by MrKalten** [comment]
This is probably related to this : "MaxCDN is shut down right now, so in the meanwhile use a different CDN or download the assets. (See https://github.com/twitter/twemoji/issues/580)."

The last version of Emoji Button ("@joeattardi/emoji-button": "^4.6.4",) uses twemoji v 12.1 ("@types/twemoji": "^12.1.2")


The CDN stopped working yesterday. So all the "emoji-button" implementation are broken. I am in this situation.

Regards,

**Comment by joeattardi** [comment]
@MrKalten No, it's not related to that - @Punisheroot is loading the files from unpkg.

By the way, unless there is a specific use case you have, I strongly recommend you upgrade to picmo (the old package @joeattardi/emoji-button is deprecated).
