### ISSUE TITLE
The picker doesn't open on macOS Catalina

### ISSUE THREAD

**Issue by dEEpProjects** [joeattardi/picmo#256]
On **macOS Catalina (Safari 13.1.2)**, the picker doesn't load and launches the following exceptions:

<img width="1054" alt="Schermata 2023-01-25 alle 09 05 45" src="https://user-images.githubusercontent.com/7797585/214510864-af4ab484-fa76-40e5-9a77-d51e6cf43674.png">

I'm embedding your picker on a cross-domain iframe and I'm using the IndexedDB based store.

The security error can be easily bypassed by using the in-memory data store, although I would have preferred to continue using IndexedDB.

I've checked **caniuse** and it seems that **replaceChildren** is supported by Safari 14:
https://caniuse.com/?search=replaceChildren

Although this environment is not brand new, it has only 3 years old.
The same issue happens on **iOS 13.x**.

Could you please have a look at this?

Thanks for your time and your great project.

**Comment by joeattardi** [comment]
Yikes, I never realized that `replaceChildren` was only recently widely supported. I can try to fix those parts of the code to use something with better compatibility.

**Comment by joeattardi** [comment]
Just published a new release, 5.7.3, that should resolve this issue. Please let me know or reopen if you still have issues!
