### ISSUE TITLE
Search bug when using the in-memory store

### ISSUE THREAD

**Issue by dEEpProjects** [joeattardi/picmo#261]
In some environments, due to security issues, I need to use the **in-memory store**.

If I try to search for an emoji newer than the supported emoji version on the platform, the search container shows it with a squared placeholder.

In this case, I think that the search should only include platform-supported emojis.

I created a simple [jsfiddle](https://jsfiddle.net/vxfeg5cb/) that shows the issue.

Please try to search for "troll" on a browser that doesn't support emoji 14. I've used Chrome 109 on Big Sur.

<img width="436" alt="search bug" src="https://user-images.githubusercontent.com/7797585/217231382-502b950a-5999-45fb-88f3-11f90d5c43a2.png">

It doesn't happen when I use the **IndexedDB store**.

Thanks.

**Comment by joeattardi** [comment]
The in-memory store was missing the version check in the search function, oops. Should be all set now, fixed in 5.7.6.

Really appreciate you reporting these issues!
