### ISSUE TITLE
Some labels are no longer translated when the i18n property is set in version 5.8.0

### ISSUE THREAD

**Issue by uaza** [joeattardi/picmo#266]
<img width="189" alt="image" src="https://user-images.githubusercontent.com/6545286/221352382-08b7a09f-e2b3-49ae-9fc4-92b1017ec156.png">

<img width="189" alt="image" src="https://user-images.githubusercontent.com/6545286/221352870-c986f2ad-f0e7-4382-92c3-01c58851a9a5.png">

Does not work:
```
emojiPicker = picmoPopup.createPopup({
                  i18n: 'en'
              }, ...
```

If you remove the i18n property, the missing translations appear again:
```
emojiPicker = picmoPopup.createPopup({}, ...
```

PS: The integrated languages with the new version 5.8.0 are great, thank you!

**Comment by joeattardi** [comment]
The `i18n` option isn't a string, it's a reference to the translated strings object itself.

It defaults to English, otherwise you need to import the `i18n` object from `picmo` and use the corresponding language, i.e. `i18n.de`, `i18n.fr`, etc.
