### ISSUE TITLE
Initial emoji missing

### ISSUE THREAD

**Issue by 3nematix** [joeattardi/picmo#267]
const picker = window.createPicker({ rootElement, emojisPerRow: 13, visibleRows: 4, emojiSize: '1.45rem', showCategoryTabs:false, className: 'my-picker', showPreview:true,  initialCategory: "people-body", initialEmoji: "👋",});

**Comment by joeattardi** [comment]
You didn't give any additional details so I am assuming you're using the latest version of PicMo. 

Are you using the UMD version or with a bundler using npm?

I tried your code in the following CodeSandbox and it seems to be working as expected:

https://codesandbox.io/s/picmo-initial-emoji-test-7ojund?file=/src/index.js

Maybe there is a misunderstanding about the functionality? What is the behavior you're expecting to see?

**Comment by joeattardi** [comment]
No response for 3 weeks, closing issue.
