### ISSUE TITLE
Sveltekit Reference Error window is not defined 

### ISSUE THREAD

**Issue by laxadev** [joeattardi/picmo#269]
I'm using SvelteKit and since I moved to version 5.8.0 from 5.7.5 the site throws this error when I hard refresh the site.

`ReferenceError: window is not defined
  File "/Projects/sveltekit-sk/node_modules/picmo/dist/index.js", line 287, in <anonymous>
    '{snip} le.warn("[picmo] sessionStorage not available, falling back to simple in-memory storage"), Object.defineProperty(window, "sessionStorage", {
  File "node:internal/modules/esm/module_job", line 194, in ModuleJob.run`

It is working perfectly fine with version 5.7.5 but with the latest or with 5.7.6 I get this.

**Comment by joeattardi** [comment]
Oops! I added some checks for local storage, looks like I missed the case when running on the server (the check involves accessing the `window` object). This should be an easy fix. Thanks for reporting!

**Comment by joeattardi** [comment]
Not sure if you can share your code but I created a quick test SvelteKit project and as long as I create the picker in `onMount` in a component, the picker is created and I don't see the error.

Can you share some code showing how you're using the picker in a SvelteKit app so I can try to recreate it and add the proper check?

**Comment by joeattardi** [comment]
Ah, I only tried it in development mode! Sorry, I am not super familiar with SvelteKit.

I think I've got it, after I run build and preview the picker works now without error. Should have a new release ready shortly.

**Comment by joeattardi** [comment]
Ok! Just published 5.8.1. Let me know if that solves the issue! Thanks for providing that test case.

**Comment by laxadev** [comment]
Everything is working. Thank you for your quick fix.

**Comment by joeattardi** [comment]
Awesome, again sorry about that. Thanks for using the library!
