### ISSUE TITLE
"placeholder" CSS class causes weird moving light animation

### ISSUE THREAD

**Issue by p0lloc** [joeattardi/picmo#270]
I stumbled across a weird issue where opening the popup picker would add a moving light/flash effect to other sections on my page. I have narrowed it down to a "placeholder" CSS class which I just happened to have on these components. It seems that picmo is using this class without any kind of prefix or parent rules. Rewriting my components to use something like "placeholder2" instead solved the issue. 

I am bundling the latest version. 
Thanks for a great library otherwise!

**Comment by joeattardi** [comment]
I made a fix a while back that resolved some issues with CSS class naming - it added a unique prefix. Looks like I have missed a spot. Hopefully this will be an easy fix!

**Comment by joeattardi** [comment]
Are you sure you're using the latest version? I'm not able to reproduce this.

Or, maybe it's something about the way you're bundling it.

Can you verify what version of PicMo you are running, and possibly create a simple codepen/codesandbox showing the issue?

**Comment by p0lloc** [comment]
Sorry! I was certain that I was using the latest version, but it turns out I was using 5.7.2. Looking back at releases, it seems that 5.7.4 solved this issue. Updating to the actual latest version resolved this issue, my bad!
