### ISSUE TITLE
Emoji Cutoff on mobile devices

### ISSUE THREAD

**Issue by bibingsoft** [joeattardi/picmo#272]
some emojis are cutoff on mobile devices. Please refer the below screenshot
![image](https://user-images.githubusercontent.com/107548849/229985066-4c1e61d0-7b4d-4591-b7f4-29a44a86c60d.png)

**Comment by joeattardi** [comment]
The emoji isn't cut off, that is how it appears on Apple devices:

https://emojipedia.org/saluting-face/

**Comment by bibingsoft** [comment]
Many thanks for your update
