### ISSUE TITLE
className is not applied to placeholder UI

### ISSUE THREAD

**Issue by jmlee2k** [joeattardi/picmo#273]
This results in a flash of the base theme while loading (when using a custom theme):

https://codesandbox.io/s/jovial-banach-fpcvp3

![picmo-bug](https://user-images.githubusercontent.com/7396545/234605779-45784f80-a4b4-42da-825f-28bb06eebe45.gif)

**Comment by joeattardi** [comment]
Thanks for the PR, I just published a new version that includes your change.
