### ISSUE TITLE
Broken Twemoji images

### ISSUE THREAD

**Issue by traone** [joeattardi/picmo#276]
Hi,
I've recently found out that there are some broken or missing Twemoji images that Picmo is referring to when one selects an emoji. Not sure if this is a hosting issue or Twitter has removed them from the CDN by accident.

Here are some broken urls that our QA team found while testing our site this week. Seems that these can also be reproduced in the Twemoji Storybook app.

https://twemoji.maxcdn.com/v/latest/svg/1fae1.svg
https://twemoji.maxcdn.com/v/latest/svg/1fae5.svg
https://twemoji.maxcdn.com/v/latest/svg/1fae0.svg
https://twemoji.maxcdn.com/v/latest/svg/1f972.svg
https://twemoji.maxcdn.com/v/latest/svg/1fae2.svg
https://twemoji.maxcdn.com/v/latest/svg/1f636-200d-1f32b-fe0f.svg
https://twemoji.maxcdn.com/v/latest/svg/1f62e-200d-1f4a8.svg

**Comment by joeattardi** [comment]
What version of PicMo are you running? If you upgrade to the latest (or at least, 5.3.0 or later) - the Twemoji renderer uses a sprite sheet built during the build process and shouldn't be reaching out to a CDN for Twemoji images.

**Comment by traone** [comment]
The picker works fine as you mentioned it is using the sprite sheet, but the `emoji.url` value for certain emoji's that point to the individual CDN hosted svg image are broken on some cases. 

![image](https://user-images.githubusercontent.com/149879/236410586-f1cac993-bc86-4523-b2f2-02d608007dba.png)

Example from the Storybook when I picked melting face.

![image](https://user-images.githubusercontent.com/149879/236412289-fef037a4-ad22-4a63-8267-374a3109b987.png)

Example from our QA.

**Comment by traone** [comment]
Could it be that these images don't even exist as of yet?

Had a look at the Twemoji repository and the latest set of added assets was Mar 11, 2022. So the case might be that Twitter is lagging behind with the design work. Taking into account the state of the company at the moment it might take a while to catch up 😄

**Comment by joeattardi** [comment]
Oh! I see it now.

I found an issue in the Twemoji repo: https://github.com/twitter/twemoji/issues/580#issuecomment-1481527718

They say the repo is no longer maintained by Twitter. There is a fork, though; I'm going to look into switching to the fork.

Thanks1

**Comment by joeattardi** [comment]
Using the forked version seems to resolve this issue. I will package up a new release.

**Comment by joeattardi** [comment]
This should now be fixed in the just-released 5.8.4.

**Comment by traone** [comment]
I can confirm this is fixed now. Thanks for the prompt fix!
