### ISSUE TITLE
[Feature] Initial emoji

### ISSUE THREAD

**Issue by qortex** [joeattardi/picmo#72]
It would be interesting to be able to set the initial emoji. Right now, it's possible to have `initialCategory`. Would a `initialEmoji` make sense for you?

My use case: avatar picker, so I'd like to open the picker at the place where the currently selected avatar is at.

**Comment by joeattardi** [comment]
Will try to get this in for 5.0.0!

**Comment by joeattardi** [comment]
This has been implemented and will be included in the next 5.0.0 beta (as well as the final release!)
